---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  attributes:
    nginx:
      default_site_enabled: false

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[cs312-testcookbook::default]
  - name: wiki
    run_list:
      - recipe[cs312-testcookbook::wiki]
    driver_config:
      network:
        - ["forwarded_port", {guest: 8080, host: 8080}]
